[package]
name = "testimages"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.56"
axum = { version = "0.8.1", features = ["http2"] }
tokio = { version = "1.17.0", features = ["full"] }

[build-dependencies]
anyhow = "1.0.56"
